# GitHub Sponsors
# github: omnicmd

# Buy Me a Coffee
# buymeacoffee: omnicmd

# Ko-fi
# ko_fi: omnicmd

# Custom donation platforms (Pix, Crypto, etc.)
custom:
  - https://ko-fi.com/omnicmd
  - https://www.buymeacoffee.com/omnicmd
